<a href="https://colab.research.google.com/github/nainye/nlp_practice/blob/main/matrix_equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EVN

In [1]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

# 행렬연산

## 데이터

In [2]:
hidden = np.random.randint(-9, 10, (5, 4)) / 10
hidden

array([[-0.7,  0.1,  0. ,  0.3],
       [-0.4,  0.2,  0.4, -0.8],
       [ 0.4, -0.4, -0.8, -0.3],
       [-0.5, -0.3,  0.9,  0.6],
       [ 0.8,  0.4, -0.4,  0.9]])

## element wise sum

In [3]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden + arg

(array([[-0.1,  0.4, -0.6,  0.3],
        [ 0.4, -0.7,  0.4, -0.7],
        [ 0.4,  0.6,  0.8, -0.2],
        [ 0.5,  0.8,  0.2,  0.5],
        [ 0.9,  0. ,  0.1,  0. ]]), array([[-0.8,  0.5, -0.6,  0.6],
        [ 0. , -0.5,  0.8, -1.5],
        [ 0.8,  0.2,  0. , -0.5],
        [ 0. ,  0.5,  1.1,  1.1],
        [ 1.7,  0.4, -0.3,  0.9]]))

In [4]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
arg, hidden + arg

(array([[-0.5,  0. , -0.2,  0.4]]), array([[-1.2,  0.1, -0.2,  0.7],
        [-0.9,  0.2,  0.2, -0.4],
        [-0.1, -0.4, -1. ,  0.1],
        [-1. , -0.3,  0.7,  1. ],
        [ 0.3,  0.4, -0.6,  1.3]]))

In [5]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden + arg

(array([[ 0.2],
        [ 0.6],
        [ 0.2],
        [ 0. ],
        [-0.1]]), array([[-0.5,  0.3,  0.2,  0.5],
        [ 0.2,  0.8,  1. , -0.2],
        [ 0.6, -0.2, -0.6, -0.1],
        [-0.5, -0.3,  0.9,  0.6],
        [ 0.7,  0.3, -0.5,  0.8]]))

In [6]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden + arg

(array([[0.1]]), array([[-0.6,  0.2,  0.1,  0.4],
        [-0.3,  0.3,  0.5, -0.7],
        [ 0.5, -0.3, -0.7, -0.2],
        [-0.4, -0.2,  1. ,  0.7],
        [ 0.9,  0.5, -0.3,  1. ]]))

In [7]:
hidden + 1

array([[0.3, 1.1, 1. , 1.3],
       [0.6, 1.2, 1.4, 0.2],
       [1.4, 0.6, 0.2, 0.7],
       [0.5, 0.7, 1.9, 1.6],
       [1.8, 1.4, 0.6, 1.9]])

In [8]:
1 + hidden

array([[0.3, 1.1, 1. , 1.3],
       [0.6, 1.2, 1.4, 0.2],
       [1.4, 0.6, 0.2, 0.7],
       [0.5, 0.7, 1.9, 1.6],
       [1.8, 1.4, 0.6, 1.9]])

## element wise multiplication

In [9]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden * arg

(array([[ 0. ,  0. , -0.8, -0.9],
        [-0.2,  0.4,  0.4,  0.3],
        [ 0.7,  0.8,  0.1,  0.2],
        [ 0.4, -0.6, -0.1, -0.6],
        [ 0.1, -0.7, -0.7,  0. ]]), array([[-0.  ,  0.  , -0.  , -0.27],
        [ 0.08,  0.08,  0.16, -0.24],
        [ 0.28, -0.32, -0.08, -0.06],
        [-0.2 ,  0.18, -0.09, -0.36],
        [ 0.08, -0.28,  0.28,  0.  ]]))

In [10]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
arg, hidden * arg

(array([[ 0.8, -0.8, -0.4,  0.6]]), array([[-0.56, -0.08, -0.  ,  0.18],
        [-0.32, -0.16, -0.16, -0.48],
        [ 0.32,  0.32,  0.32, -0.18],
        [-0.4 ,  0.24, -0.36,  0.36],
        [ 0.64, -0.32,  0.16,  0.54]]))

In [11]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden * arg

(array([[ 0. ],
        [ 0.9],
        [-0.7],
        [-0.4],
        [-0.4]]), array([[-0.  ,  0.  ,  0.  ,  0.  ],
        [-0.36,  0.18,  0.36, -0.72],
        [-0.28,  0.28,  0.56,  0.21],
        [ 0.2 ,  0.12, -0.36, -0.24],
        [-0.32, -0.16,  0.16, -0.36]]))

In [12]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden * arg

(array([[-0.8]]), array([[ 0.56, -0.08, -0.  , -0.24],
        [ 0.32, -0.16, -0.32,  0.64],
        [-0.32,  0.32,  0.64,  0.24],
        [ 0.4 ,  0.24, -0.72, -0.48],
        [-0.64, -0.32,  0.32, -0.72]]))

In [13]:
hidden * 2

array([[-1.4,  0.2,  0. ,  0.6],
       [-0.8,  0.4,  0.8, -1.6],
       [ 0.8, -0.8, -1.6, -0.6],
       [-1. , -0.6,  1.8,  1.2],
       [ 1.6,  0.8, -0.8,  1.8]])

In [14]:
2 * hidden

array([[-1.4,  0.2,  0. ,  0.6],
       [-0.8,  0.4,  0.8, -1.6],
       [ 0.8, -0.8, -1.6, -0.6],
       [-1. , -0.6,  1.8,  1.2],
       [ 1.6,  0.8, -0.8,  1.8]])

## matrix multiplication

In [15]:
hidden

array([[-0.7,  0.1,  0. ,  0.3],
       [-0.4,  0.2,  0.4, -0.8],
       [ 0.4, -0.4, -0.8, -0.3],
       [-0.5, -0.3,  0.9,  0.6],
       [ 0.8,  0.4, -0.4,  0.9]])

In [16]:
arg = np.random.randint(-9, 10, (4, 5)) / 10
arg, np.matmul(hidden, arg)

(array([[-0.3,  0.3,  0.4, -0.4, -0.8],
        [-0.5, -0.6,  0.9, -0.3, -0.2],
        [-0.4, -0.1,  0.9,  0.7,  0.4],
        [ 0.1, -0.9, -0.7, -0.6,  0.8]]),
 array([[ 1.90000000e-01, -5.40000000e-01, -4.00000000e-01,
          7.00000000e-02,  7.80000000e-01],
        [-2.20000000e-01,  4.40000000e-01,  9.40000000e-01,
          8.60000000e-01, -2.00000000e-01],
        [ 3.70000000e-01,  7.10000000e-01, -7.10000000e-01,
         -4.20000000e-01, -8.00000000e-01],
        [-3.83026943e-17, -6.00000000e-01, -8.00000000e-02,
          5.60000000e-01,  1.30000000e+00],
        [-1.90000000e-01, -7.70000000e-01, -3.10000000e-01,
         -1.26000000e+00, -1.60000000e-01]]))

In [17]:
val = np.zeros((hidden.shape[0], arg.shape[1]))
val

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
for row in range(hidden.shape[0]):
    row_v = hidden[row]
    for col in range(arg.shape[1]):
        col_v = arg[:, col]
        val[row][col] = np.dot(row_v, col_v)
val

array([[ 1.90000000e-01, -5.40000000e-01, -4.00000000e-01,
         7.00000000e-02,  7.80000000e-01],
       [-2.20000000e-01,  4.40000000e-01,  9.40000000e-01,
         8.60000000e-01, -2.00000000e-01],
       [ 3.70000000e-01,  7.10000000e-01, -7.10000000e-01,
        -4.20000000e-01, -8.00000000e-01],
       [-5.55111512e-17, -6.00000000e-01, -8.00000000e-02,
         5.60000000e-01,  1.30000000e+00],
       [-1.90000000e-01, -7.70000000e-01, -3.10000000e-01,
        -1.26000000e+00, -1.60000000e-01]])